### ISSUE TITLE
title

### ISSUE THREAD

**Issue by Netznarkose** [Netznarkose/dotfiles#2]

**Comment by kotp** [comment]
```ruby
raise ArgumentError, 'The two strands must have the same length.' unless
  strand_a.size == strand_b.size
```

You could also create a `LengthError` class that inherits from `StandardError` that has a close to appropriate method, and give some details that you would like to share, like lengths of each item, etc.  Having the work done there removes the work from the code where the error could happen, and gives opportunities for communication.
